### ISSUE TITLE
Is it possible to access servers inside of private network with this ssh client?

### ISSUE THREAD

**Issue by aleksandrlat** [hullarb/ssheasy#1]
Is it possible to access servers inside of private network with this ssh client?

**Comment by hullarb** [comment]
it's possible if you install it within the private network. the public instance ssheasy.com can only access servers that are accessible from the public internet.

**Comment by aleksandrlat** [comment]
Thank you @hullarb!

But what do you mean by install? Is this not just web app?

**Comment by aleksandrlat** [comment]
Oh sorry I have not read description well enough
It needs proxy server because it is not possible to connect from browser to ssh server directly.

**Comment by hullarb** [comment]
yes, @aleksandrlat  and the proxy server needs to have access to the network of the target ssh server.

**Comment by aleksandrlat** [comment]
Thank you @hullarb!

Do you know if there is way to do it without proxy server?
The client is downloaded to browser right? And if my browser is inside of private network ssh client should be able to access my server
But it is not possible to do because I cannot establish ssh connection directly from browser, right?

**Comment by hullarb** [comment]
yes, from the browser (more like from javascript/wasm) you cannot open raw socket connection, you can only make http requests that would not work with ssh.
it should be fairly easy to setup the server on (desktop) computer if you have docker installed on it. if you need help with that let me know.

**Comment by aleksandrlat** [comment]
Thank you @hullarb!
