### ISSUE TITLE
is IPv6 supported ?

### ISSUE THREAD

**Issue by tbox1911** [hullarb/ssheasy#12]
hi,very nice tool,
work fine with IPv4 host but throw an error when I try to connect IPv6 host

error:
cannot connect to host: dial tcp [2a02:8429:614a:6901:ba27:ebff:xxxxx:xxxxx]:22: connect: cannot assign requested address

**Comment by hullarb** [comment]
Hi,

Thank you for your question and the feedback.
Currently IPv6 is not supported indeed.

**Comment by Atticuss26** [comment]
will it be supported in the future?

**Comment by hullarb** [comment]
yes, it's planned, but timeline is not clear yet.

**Comment by hullarb** [comment]
ipv6 support was enabled on ssheasy.com

in case of running ssheasy yourself you need to ensure that IPv6 is configured on the host and enabled in docker as well (https://docs.docker.com/config/daemon/ipv6/)
