### ISSUE TITLE
Is it possible to make a ssheasy using Php?

### ISSUE THREAD

**Issue by SunnySkai** [hullarb/ssheasy#16]

**Comment by hullarb** [comment]
Hi,

I'm not sure what you exactly mean. do you mean if the backend of ssheasy could be implemented in PHP?

**Comment by SunnySkai** [comment]
I mean, Could u tell me the possibility to make the project similar to the ssheasy.com with php frameworks like Laravel?
Backend is Laravel and frontend is ... jQuery.

**Comment by hullarb** [comment]
i cannot really give you advice on that, i suppose you could write the backend in PHP as well, but i have not much experience with PHP.
