### ISSUE TITLE
Can not download Large file

### ISSUE THREAD

**Issue by todeveloper21** [hullarb/ssheasy#4]
can not download 30MB > files

**Comment by hullarb** [comment]
hi,

Thanks for reporting an issue. I did few test and i don't see any issue, up- and downloads were working fine even with much larger files.
did this happen multiple times for you? isn't possible that you had network interruption either on your client side or on server side?

Bela

**Comment by hullarb** [comment]
is the issue still happening for you? do you have any update on it?
