### ISSUE TITLE
Send SSH Command programmatic from browser

### ISSUE THREAD

**Issue by xnohat** [hullarb/ssheasy#6]
Hi,
SSHEasy now wasm ssh client and run entirely in browser, so can I using ssheasy to send an ssh command programmatically from my browser to my local ssh server in a local network where I open ssheasy.com in same local network ?

Thanks,

**Comment by hullarb** [comment]
Hi,
Unfortunately this is not possible, the server under ssheasy is on the internet and has no access to your local network. To be able to connect to your server that has to be accessible from the outside, so you would need to configure port forwarding or some other solution on your router to allow external access to your server.

Regards,
Bela
